package com.msam.ringkesin.ui.localization

/**
 * Simple UI text localization for Ringkesin.
 * All text is defined in both ID and EN.
 */
object S {
    fun tapToRecord(lang: String) = if (lang == "en") "Tap to start recording" else "Ketuk untuk mulai merekam"
    fun listening(lang: String) = if (lang == "en") "Listening..." else "Mendengarkan..."
    fun preparing(lang: String) = if (lang == "en") "Preparing..." else "Menyiapkan..."
    fun recordingComplete(lang: String) = if (lang == "en") "Recording complete" else "Rekaman selesai"
    fun recordingStopped(lang: String) = if (lang == "en") "Recording stopped" else "Rekaman dihentikan"
    fun stop(lang: String) = if (lang == "en") "Stop" else "Berhenti"
    fun recordingEllipsis(lang: String) = if (lang == "en") "Recording..." else "Merekam..."
    fun processing(lang: String) = if (lang == "en") "Processing..." else "Memproses..."
    fun resultEmpty(lang: String) = if (lang == "en") "No recording result" else "Tidak ada hasil rekaman"
    fun permissionRequired(lang: String) = if (lang == "en") "Microphone permission is required" else "Izin mikrofon diperlukan"
    fun tapToSpeak(lang: String) = if (lang == "en") "Tap to speak" else "Ketuk untuk bicara"
    fun preparingRecording(lang: String) = if (lang == "en") "Preparing recording..." else "Menyiapkan rekaman..."
    fun transcript(lang: String) = if (lang == "en") "Transcript" else "Transkrip"
    fun summarize(lang: String) = if (lang == "en") "Summarize with AI" else "Ringkas dengan AI"
    fun summarizing(lang: String) = if (lang == "en") "Summarizing..." else "Meringkas..."
    fun copy(lang: String) = if (lang == "en") "Copy" else "Salin"
    fun delete(lang: String) = if (lang == "en") "Delete" else "Hapus"
    fun save(lang: String) = if (lang == "en") "Save" else "Simpan"
    fun saved(lang: String) = if (lang == "en") "Saved" else "Tersimpan"
    fun summarySaved(lang: String) = if (lang == "en") "Summary saved" else "Ringkasan tersimpan"
    fun noSummary(lang: String) = if (lang == "en") "Record a session and summarize it with AI" else "Rekam sesi dan ringkas dengan AI"
    fun history(lang: String) = if (lang == "en") "History" else "Riwayat"
    fun noHistory(lang: String) = if (lang == "en") "No sessions yet" else "Belum ada sesi"
    fun settings(lang: String) = if (lang == "en") "Settings" else "Setelan"
    fun load(lang: String) = if (lang == "en") "Load" else "Muat"
    fun summaryLabel(lang: String) = if (lang == "en") "Summary" else "Ringkasan"
    fun aiSummary(lang: String) = if (lang == "en") "AI Summary" else "Ringkasan AI"
    fun transcriptOnly(lang: String) = if (lang == "en") "Transcript" else "Transkrip"
    fun loadedFromHistory(lang: String) = if (lang == "en") "Loaded from history" else "Dimuat dari riwayat"
    fun errorGeneric(lang: String) = if (lang == "en") "An error occurred" else "Terjadi kesalahan"
    fun requestPermission(lang: String) = if (lang == "en") "Grant microphone permission to record" else "Izinkan akses mikrofon untuk merekam"
    fun grantPermission(lang: String) = if (lang == "en") "Grant Permission" else "Izinkan"
    fun seconds(lang: String) = if (lang == "en") "s" else "dtk"
    fun minutes(lang: String) = if (lang == "en") "min" else "mnt"
    fun recordingInProgress(lang: String) = if (lang == "en") "Recording in progress" else "Sedang merekam"
    // Summary screen
    fun sourceTranscript(lang: String) = if (lang == "en") "Source transcript" else "Transkrip sumber"
    fun noSummaryYet(lang: String) = if (lang == "en") "No summary yet" else "Belum ada ringkasan"
    fun copied(lang: String) = if (lang == "en") "Copied!" else "Tersalin"
    fun noSummaryHint(lang: String) = if (lang == "en")
        "Record a transcript in the Record tab,\\n then summarize with AI"
    else
        "Rekam transkrip di tab Rekam,\\n lalu ringkas dengan AI"
    // Settings labels
    fun aiProvider(lang: String) = if (lang == "en") "AI Provider" else "Provider AI"
    fun apiKey(lang: String) = if (lang == "en") "API Key" else "API Key"
    fun model(lang: String) = if (lang == "en") "Model" else "Model"
    fun baseUrl(lang: String) = if (lang == "en") "Base URL" else "Base URL"
    fun theme(lang: String) = if (lang == "en") "Theme" else "Tema"
    fun uiLanguage(lang: String) = if (lang == "en") "UI Language" else "Bahasa UI"
    fun backgroundRecord(lang: String) = if (lang == "en") "Background Record" else "Rekam di background"
    fun autoSave(lang: String) = if (lang == "en") "Auto Save" else "Simpan otomatis"
    fun notification(lang: String) = if (lang == "en") "Notification" else "Notifikasi"
    fun systemPrompt(lang: String) = if (lang == "en") "System Prompt" else "Prompt Sistem"
    fun speechLanguage(lang: String) = if (lang == "en") "Speech Language" else "Bahasa speech"
    fun recording(lang: String) = if (lang == "en") "Recording" else "Rekaman"
    fun summaryComplete(lang: String) = if (lang == "en") "Summary complete" else "Ringkasan selesai"
    fun failedToSummarize(lang: String) = if (lang == "en") "Failed to summarize" else "Gagal meringkas"
    fun transcriptWillAppearHere(lang: String) = if (lang == "en") "Transcript will appear here" else "Transkrip akan muncul di sini"
    fun startSpeaking(lang: String) = if (lang == "en") "Start speaking..." else "Mulai bicara..."
    fun tabRecord(lang: String) = if (lang == "en") "Record" else "Rekam"
    fun tabSummary(lang: String) = if (lang == "en") "Summary" else "Ringkasan"
    fun tabHistory(lang: String) = if (lang == "en") "History" else "Riwayat"
    fun tabSettings(lang: String) = if (lang == "en") "Settings" else "Setelan"
    fun voiceRecording(lang: String) = if (lang == "en") "Voice Recording" else "Rekaman Suara"
    fun notificationChannelDescription(lang: String) = if (lang == "en")
        "Notification when Ringkesin is recording audio"
    else
        "Notifikasi saat Ringkesin merekam audio"
    fun apiKeyMissingInSettings(lang: String) = if (lang == "en") "Fill in API Key in Settings first" else "Isi API Key dulu di Pengaturan"
    fun apiKeyMissing(lang: String) = if (lang == "en") "API Key not filled in Settings" else "API Key belum diisi di Pengaturan"
    fun data(lang: String) = if (lang == "en") "Data" else "Data"
    fun about(lang: String) = if (lang == "en") "About" else "Tentang"
    fun exportAllData(lang: String) = if (lang == "en") "Export all data" else "Ekspor semua data"
    fun deleteAllData(lang: String) = if (lang == "en") "Delete all data" else "Hapus semua data"
    fun searchPlaceholder(lang: String) = if (lang == "en") "Search transcripts..." else "Cari transkrip..."
    fun systemPromptPlaceholder(lang: String) = if (lang == "en")
        "Default prompt will be used if empty..."
    else
        "Prompt default akan digunakan jika kosong..."
    fun version(lang: String) = if (lang == "en") "Version" else "Versi"
    fun createdBy(lang: String) = if (lang == "en") "Created by" else "Dibuat oleh"
}
